# Generated by Django 6.0.2 on 2026-02-24 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_rename_courses_student_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(default='Male', max_length=20),
        ),
    ]
