# Generated by Django 6.0.2 on 2026-02-27 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0007_alter_student_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.CharField(default=datetime.date.today),
        ),
    ]
